apiVersion: v1
kind: PersistentVolume # Create PV
metadata:
  name: pv-prometheus # Sets PV name
  namespace: monitoring-prometheus
  labels:
    type: local # Sets PV's type
    app: prometheus-server
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi # Sets PV's size
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/prometheus # Sets PV's host path
