apiVersion: v1
kind: PersistentVolume # Create PV
metadata:
  name: pv-prometheus # Sets PV name
  namespace: monitoring
  labels:
    type: local # Sets PV's type
    app: prometheus-deployment
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi # Sets PV's size
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /opt/data-nas/minikube/prometheus # Sets PV's host path
