apiVersion: skaffold/v2beta27
kind: Config
metadata:
  name: kubernetes-prometheus
deploy:
  kubectl:
    manifests:
      - namespace.yaml
      - clusterRole.yaml
      - config-map.yaml
      - prometheus-pv.yaml
      - prometheus-pvc.yaml
      - prometheus-deployment.yaml
      - prometheus-service.yaml
      - prometheus-ingress.yaml
