apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: monitoring-prometheus
spec:
  storageClassName: prometheus-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
