apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: monitoring-prometheus
  annotations:
    # cloud.google.com/backend-config: '{"default": "wb-api-backend-config"}'
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"

spec:
  selector:
    app: prometheus-server
  type: NodePort
  ports:
    - port: 80
      targetPort: 9090
      protocol: TCP
  #     nodePort: 30000
